services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'ui'
    ports:
      - "5173:5173"
    env_file:
      - .env
    networks:
      - app-network
networks:
  app-network:
    external: true
    name: app-network
    driver: bridge